eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8060/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10 #发送心跳的频率
    health-check-url-path: /actuator/health
provider:
#  host: http://PROVIDER
  host: PROVIDER
  orderBriefInfoURL: /order/order-brief-info
  testPostURL: /test/insert