eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8060/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10 #发送心跳的频率
    health-check-url-path: /actuator/health
spring:
  datasource:
    url: jdbc:mariadb://192.168.0.110:3306/provider_database
    username: root
    password: root